# coding: utf-8

"""
    Events Ingestion API

    The Observation platform's Events Ingestion API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@datakitchen.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import events_ingestion_client
from events_ingestion_client.models.run_state_event_schema_request_body import RunStateEventSchemaRequestBody  # noqa: E501
from events_ingestion_client.rest import ApiException


class TestRunStateEventSchemaRequestBody(unittest.TestCase):
    """RunStateEventSchemaRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunStateEventSchemaRequestBody(self):
        """Test RunStateEventSchemaRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = events_ingestion_client.models.run_state_event_schema_request_body.RunStateEventSchemaRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
