
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-04T19:50:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a0ecfdb71b257a6c507806c06c434fe77604aacf",
 "version": "6.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
