
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-01T08:33:21+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "793cdf63fb38e2cd37869e3084701f4c120f0c38",
 "version": "0.3.0.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
