# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfx/proto/orchestration/garbage_collection_policy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tfx/proto/orchestration/garbage_collection_policy.proto',
  package='tfx.orchestration',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n7tfx/proto/orchestration/garbage_collection_policy.proto\x12\x11tfx.orchestration\"\xa6\x05\n\x17GarbageCollectionPolicy\x12l\n\x1ckeep_most_recently_published\x18\x01 \x01(\x0b\x32\x44.tfx.orchestration.GarbageCollectionPolicy.KeepMostRecentlyPublishedH\x00\x12h\n\x1akeep_property_value_groups\x18\x02 \x01(\x0b\x32\x42.tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroupsH\x00\x1a\x32\n\x19KeepMostRecentlyPublished\x12\x15\n\rnum_artifacts\x18\x01 \x01(\x05\x1a\xf4\x02\n\x17KeepPropertyValueGroups\x12^\n\tgroupings\x18\x01 \x03(\x0b\x32K.tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroups.Grouping\x1a\xf8\x01\n\x08Grouping\x12\x15\n\rproperty_name\x18\x01 \x01(\t\x12\x10\n\x08keep_num\x18\x02 \x01(\x05\x12i\n\nkeep_order\x18\x03 \x01(\x0e\x32U.tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroups.Grouping.KeepOrder\"X\n\tKeepOrder\x12\x1a\n\x16KEEP_ORDER_UNSPECIFIED\x10\x00\x12\x16\n\x12KEEP_ORDER_LARGEST\x10\x01\x12\x17\n\x13KEEP_ORDER_SMALLEST\x10\x02\x42\x08\n\x06policyb\x06proto3')
)



_GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING_KEEPORDER = _descriptor.EnumDescriptor(
  name='KeepOrder',
  full_name='tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroups.Grouping.KeepOrder',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KEEP_ORDER_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEEP_ORDER_LARGEST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KEEP_ORDER_SMALLEST', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=659,
  serialized_end=747,
)
_sym_db.RegisterEnumDescriptor(_GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING_KEEPORDER)


_GARBAGECOLLECTIONPOLICY_KEEPMOSTRECENTLYPUBLISHED = _descriptor.Descriptor(
  name='KeepMostRecentlyPublished',
  full_name='tfx.orchestration.GarbageCollectionPolicy.KeepMostRecentlyPublished',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_artifacts', full_name='tfx.orchestration.GarbageCollectionPolicy.KeepMostRecentlyPublished.num_artifacts', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=372,
)

_GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING = _descriptor.Descriptor(
  name='Grouping',
  full_name='tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroups.Grouping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='property_name', full_name='tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroups.Grouping.property_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keep_num', full_name='tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroups.Grouping.keep_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keep_order', full_name='tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroups.Grouping.keep_order', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING_KEEPORDER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=747,
)

_GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS = _descriptor.Descriptor(
  name='KeepPropertyValueGroups',
  full_name='tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroups',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupings', full_name='tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroups.groupings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=747,
)

_GARBAGECOLLECTIONPOLICY = _descriptor.Descriptor(
  name='GarbageCollectionPolicy',
  full_name='tfx.orchestration.GarbageCollectionPolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keep_most_recently_published', full_name='tfx.orchestration.GarbageCollectionPolicy.keep_most_recently_published', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keep_property_value_groups', full_name='tfx.orchestration.GarbageCollectionPolicy.keep_property_value_groups', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GARBAGECOLLECTIONPOLICY_KEEPMOSTRECENTLYPUBLISHED, _GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='policy', full_name='tfx.orchestration.GarbageCollectionPolicy.policy',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=79,
  serialized_end=757,
)

_GARBAGECOLLECTIONPOLICY_KEEPMOSTRECENTLYPUBLISHED.containing_type = _GARBAGECOLLECTIONPOLICY
_GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING.fields_by_name['keep_order'].enum_type = _GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING_KEEPORDER
_GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING.containing_type = _GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS
_GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING_KEEPORDER.containing_type = _GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING
_GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS.fields_by_name['groupings'].message_type = _GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING
_GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS.containing_type = _GARBAGECOLLECTIONPOLICY
_GARBAGECOLLECTIONPOLICY.fields_by_name['keep_most_recently_published'].message_type = _GARBAGECOLLECTIONPOLICY_KEEPMOSTRECENTLYPUBLISHED
_GARBAGECOLLECTIONPOLICY.fields_by_name['keep_property_value_groups'].message_type = _GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS
_GARBAGECOLLECTIONPOLICY.oneofs_by_name['policy'].fields.append(
  _GARBAGECOLLECTIONPOLICY.fields_by_name['keep_most_recently_published'])
_GARBAGECOLLECTIONPOLICY.fields_by_name['keep_most_recently_published'].containing_oneof = _GARBAGECOLLECTIONPOLICY.oneofs_by_name['policy']
_GARBAGECOLLECTIONPOLICY.oneofs_by_name['policy'].fields.append(
  _GARBAGECOLLECTIONPOLICY.fields_by_name['keep_property_value_groups'])
_GARBAGECOLLECTIONPOLICY.fields_by_name['keep_property_value_groups'].containing_oneof = _GARBAGECOLLECTIONPOLICY.oneofs_by_name['policy']
DESCRIPTOR.message_types_by_name['GarbageCollectionPolicy'] = _GARBAGECOLLECTIONPOLICY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GarbageCollectionPolicy = _reflection.GeneratedProtocolMessageType('GarbageCollectionPolicy', (_message.Message,), {

  'KeepMostRecentlyPublished' : _reflection.GeneratedProtocolMessageType('KeepMostRecentlyPublished', (_message.Message,), {
    'DESCRIPTOR' : _GARBAGECOLLECTIONPOLICY_KEEPMOSTRECENTLYPUBLISHED,
    '__module__' : 'tfx.proto.orchestration.garbage_collection_policy_pb2'
    # @@protoc_insertion_point(class_scope:tfx.orchestration.GarbageCollectionPolicy.KeepMostRecentlyPublished)
    })
  ,

  'KeepPropertyValueGroups' : _reflection.GeneratedProtocolMessageType('KeepPropertyValueGroups', (_message.Message,), {

    'Grouping' : _reflection.GeneratedProtocolMessageType('Grouping', (_message.Message,), {
      'DESCRIPTOR' : _GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS_GROUPING,
      '__module__' : 'tfx.proto.orchestration.garbage_collection_policy_pb2'
      # @@protoc_insertion_point(class_scope:tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroups.Grouping)
      })
    ,
    'DESCRIPTOR' : _GARBAGECOLLECTIONPOLICY_KEEPPROPERTYVALUEGROUPS,
    '__module__' : 'tfx.proto.orchestration.garbage_collection_policy_pb2'
    # @@protoc_insertion_point(class_scope:tfx.orchestration.GarbageCollectionPolicy.KeepPropertyValueGroups)
    })
  ,
  'DESCRIPTOR' : _GARBAGECOLLECTIONPOLICY,
  '__module__' : 'tfx.proto.orchestration.garbage_collection_policy_pb2'
  # @@protoc_insertion_point(class_scope:tfx.orchestration.GarbageCollectionPolicy)
  })
_sym_db.RegisterMessage(GarbageCollectionPolicy)
_sym_db.RegisterMessage(GarbageCollectionPolicy.KeepMostRecentlyPublished)
_sym_db.RegisterMessage(GarbageCollectionPolicy.KeepPropertyValueGroups)
_sym_db.RegisterMessage(GarbageCollectionPolicy.KeepPropertyValueGroups.Grouping)


# @@protoc_insertion_point(module_scope)
