
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-02T17:59:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d7c5cfeaf0fa671d9d521f510b179497bb22477",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
