WORKSPACE_ENDPOINT = "/workspace"
SINGLE_WORKSPACE_ENDPOINT = WORKSPACE_ENDPOINT + "/{workspace_guid}"
WORKSPACE_APPS_ENDPOINT = WORKSPACE_ENDPOINT + "/{workspace_guid}/apps"
WORKSPACE_INDICES_ENDPOINT = WORKSPACE_ENDPOINT + "/{workspace_guid}/indices"
