
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-04T09:45:41-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "35a06faca60d3c4ee89459999cb8b207a7690505",
 "version": "1.0.4.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
