VERSION_YEAR = 2023
VERSION_MONTH = int('05')
VERSION_DAY = int('02')
VERSION_HOUR = int('18')
VERSION_MINUTE = int('37')
MAJOR_VERSION = 0
MINOR_VERSION = 2
PATCH_VERSION = 202305021837
version_date = '2023/05/02 18:37'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
