# Form implementation generated from reading ui file 'ttc2sfnt_options_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ttc2sfntOptions_Dialog(object):
    def setupUi(self, ttc2sfntOptions_Dialog):
        ttc2sfntOptions_Dialog.setObjectName("ttc2sfntOptions_Dialog")
        ttc2sfntOptions_Dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(9)
        ttc2sfntOptions_Dialog.setFont(font)
        ttc2sfntOptions_Dialog.setSizeGripEnabled(False)
        ttc2sfntOptions_Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(ttc2sfntOptions_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 434, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.overwrite_checkBox = QtWidgets.QCheckBox(parent=ttc2sfntOptions_Dialog)
        self.overwrite_checkBox.setObjectName("overwrite_checkBox")
        self.gridLayout.addWidget(self.overwrite_checkBox, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ttc2sfntOptions_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.RestoreDefaults|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.inputFormat_label = QtWidgets.QLabel(parent=ttc2sfntOptions_Dialog)
        self.inputFormat_label.setObjectName("inputFormat_label")
        self.gridLayout.addWidget(self.inputFormat_label, 0, 0, 1, 1)
        self.recalcTimestamp_checkBox = QtWidgets.QCheckBox(parent=ttc2sfntOptions_Dialog)
        self.recalcTimestamp_checkBox.setObjectName("recalcTimestamp_checkBox")
        self.gridLayout.addWidget(self.recalcTimestamp_checkBox, 2, 0, 1, 1)

        self.retranslateUi(ttc2sfntOptions_Dialog)
        self.buttonBox.accepted.connect(ttc2sfntOptions_Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ttc2sfntOptions_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ttc2sfntOptions_Dialog)
        ttc2sfntOptions_Dialog.setTabOrder(self.overwrite_checkBox, self.recalcTimestamp_checkBox)

    def retranslateUi(self, ttc2sfntOptions_Dialog):
        _translate = QtCore.QCoreApplication.translate
        ttc2sfntOptions_Dialog.setWindowTitle(_translate("ttc2sfntOptions_Dialog", "TTC to SFNT options"))
        self.overwrite_checkBox.setText(_translate("ttc2sfntOptions_Dialog", "Overwrite existing files"))
        self.inputFormat_label.setText(_translate("ttc2sfntOptions_Dialog", "Input format"))
        self.recalcTimestamp_checkBox.setText(_translate("ttc2sfntOptions_Dialog", "Recalc timestamp"))
