# Generated by Django 4.2 on 2023-04-20 14:13

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="literature",
            name="published",
            field=models.DateField(
                blank=True,
                max_length=255,
                null=True,
                validators=[django.core.validators.MaxValueValidator(datetime.date.today)],
                verbose_name="date published",
            ),
        ),
    ]
