# Generated by Django 4.2 on 2023-04-24 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("literature", "0004_remove_literature_doi_remove_literature_isbn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="literature",
            name="PID",
        ),
        migrations.RemoveField(
            model_name="literature",
            name="PID_type",
        ),
        migrations.RemoveField(
            model_name="literature",
            name="URL",
        ),
    ]
