
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-04T11:07:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "93015cb3756562e066bb63751409e80499985d6d",
 "version": "2.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
