
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-04T13:29:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0148460b17818f8ec4ede05ff3f7af4d3e465a3",
 "version": "2.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
