
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-03T15:44:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e051e5d02310b4b36976456e7a30fd4a02a9453",
 "version": "0.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
