# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ho_protocols/live/sensors.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fho_protocols/live/sensors.proto\x12\x0fho.live.sensors\"\xfb\x01\n\x0eSensorLiveItem\x12\x36\n\rbroodnest_tmp\x18\x01 \x01(\x0b\x32\x1d.ho.live.sensors.BroodnestTmpH\x00\x12\x36\n\rbroodnest_pwr\x18\x02 \x01(\x0b\x32\x1d.ho.live.sensors.BroodnestPwrH\x00\x12\x36\n\rbroodnest_rht\x18\x03 \x01(\x0b\x32\x1d.ho.live.sensors.BroodnestRhtH\x00\x12\x36\n\rbroodnest_co2\x18\x04 \x01(\x0b\x32\x1d.ho.live.sensors.BroodnestCO2H\x00\x42\t\n\x07sensors\"\x1c\n\x0c\x42roodnestTmp\x12\x0c\n\x04temp\x18\x01 \x03(\x02\"V\n\x0c\x42roodnestPwr\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\x02\x12\r\n\x05power\x18\x02 \x01(\x02\x12\x15\n\rshunt_voltage\x18\x03 \x01(\x02\x12\x0f\n\x07voltage\x18\x04 \x01(\x02\"6\n\x0c\x42roodnestRht\x12\x11\n\trel_humid\x18\x01 \x01(\x02\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\"C\n\x0c\x42roodnestCO2\x12\x0b\n\x03\x63o2\x18\x01 \x01(\x02\x12\x11\n\trel_humid\x18\x02 \x01(\x02\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ho_protocols.live.sensors_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _globals['_SENSORLIVEITEM']._serialized_start=53
  _globals['_SENSORLIVEITEM']._serialized_end=304
  _globals['_BROODNESTTMP']._serialized_start=306
  _globals['_BROODNESTTMP']._serialized_end=334
  _globals['_BROODNESTPWR']._serialized_start=336
  _globals['_BROODNESTPWR']._serialized_end=422
  _globals['_BROODNESTRHT']._serialized_start=424
  _globals['_BROODNESTRHT']._serialized_end=478
  _globals['_BROODNESTCO2']._serialized_start=480
  _globals['_BROODNESTCO2']._serialized_end=547
# @@protoc_insertion_point(module_scope)
