# (generated with --quick)

import gymnasium as gym
import torch as th
from hsuanwu.xploit.agent import utils
from torch import nn
from torch.nn import functional as F
from typing import Any, Tuple, Union

Distribution: Any

class DistributedActorCritic(Any):
    class BoxActor(Any):
        __doc__: str
        actor_logstd: Any
        actor_mu: Any
        def __init__(self, action_shape, hidden_dim) -> None: ...
        def forward(self, obs) -> Any: ...
        def get_policy_outputs(self, obs) -> Tuple[Any, Any]: ...
    class DiscreteActor(Any):
        __doc__: str
        actor: Any
        def __init__(self, action_shape, hidden_dim) -> None: ...
        def forward(self, obs) -> Any: ...
        def get_policy_outputs(self, obs) -> Any: ...
    __doc__: str
    action_dim: Any
    action_range: list
    action_type: str
    actor: Union[DistributedActorCritic.BoxActor, DistributedActorCritic.DiscreteActor]
    critic: Any
    dist: None
    encoder: None
    lstm: Any
    num_actions: Any
    policy_reshape_dim: Any
    use_lstm: bool
    def __init__(self, action_shape: tuple, action_type: str, action_range: list, feature_dim, hidden_dim: int = ..., use_lstm: bool = ...) -> None: ...
    def forward(self, inputs: dict, lstm_state: tuple = ...) -> Any: ...
    def get_action(self, inputs: dict, lstm_state: tuple = ..., training: bool = ...) -> Any: ...
    def get_dist(self, outputs) -> Any: ...
    def init_state(self, batch_size: int) -> tuple: ...

class OffPolicyDeterministicActor(Any):
    __doc__: str
    dist: None
    policy: Any
    def __init__(self, action_space, feature_dim: int = ..., hidden_dim: int = ...) -> None: ...
    def forward(self, obs) -> Any: ...
    def get_dist(self, obs, step: int) -> Any: ...

class OffPolicyDoubleCritic(Any):
    Q1: Any
    Q2: Any
    __doc__: str
    def __init__(self, action_space, feature_dim: int = ..., hidden_dim: int = ...) -> None: ...
    def forward(self, obs, action) -> tuple: ...

class OffPolicyStochasticActor(Any):
    __doc__: str
    dist: None
    log_std_max: Any
    log_std_min: Any
    policy: Any
    def __init__(self, action_space, feature_dim: int = ..., hidden_dim: int = ..., log_std_range: tuple = ...) -> None: ...
    def forward(self, obs) -> Any: ...
    def get_dist(self, obs, step: int) -> Any: ...

class OnPolicyDecoupledActorCritic(Any):
    class BoxActor(Any):
        __doc__: str
        actor_logstd: Any
        actor_mu: Any
        def __init__(self, action_shape, hidden_dim) -> None: ...
        def forward(self, obs) -> Any: ...
        def get_policy_outputs(self, obs) -> Tuple[Any, Any]: ...
    class DiscreteActor(Any):
        __doc__: str
        actor: Any
        def __init__(self, action_shape, hidden_dim) -> None: ...
        def forward(self, obs) -> Any: ...
        def get_policy_outputs(self, obs) -> Tuple[Any]: ...
    class MultiBinaryActor(Any):
        __doc__: str
        actor: Any
        def __init__(self, action_shape, hidden_dim) -> None: ...
        def forward(self, obs) -> Any: ...
        def get_policy_outputs(self, obs) -> Tuple[Any]: ...
    __doc__: str
    action_type: str
    actor: Union[OnPolicyDecoupledActorCritic.BoxActor, OnPolicyDecoupledActorCritic.DiscreteActor, OnPolicyDecoupledActorCritic.MultiBinaryActor]
    actor_encoder: None
    critic: Any
    critic_encoder: None
    dist: None
    gae: Any
    num_actions: Any
    def __init__(self, action_shape: tuple, action_type: str, feature_dim: int, hidden_dim: int) -> None: ...
    def forward(self, obs) -> Any: ...
    def get_action_and_value(self, obs, actions = ...) -> tuple: ...
    def get_det_action(self, obs) -> Any: ...
    def get_value(self, obs) -> Any: ...

class OnPolicySharedActorCritic(Any):
    class BoxActor(Any):
        __doc__: str
        actor_logstd: Any
        actor_mu: Any
        def __init__(self, action_shape, hidden_dim) -> None: ...
        def forward(self, obs) -> Any: ...
        def get_policy_outputs(self, obs) -> Tuple[Any, Any]: ...
    class DiscreteActor(Any):
        __doc__: str
        actor: Any
        def __init__(self, action_shape, hidden_dim) -> None: ...
        def forward(self, obs) -> Any: ...
        def get_policy_outputs(self, obs) -> Tuple[Any]: ...
    class MultiBinaryActor(Any):
        __doc__: str
        actor: Any
        def __init__(self, action_shape, hidden_dim) -> None: ...
        def forward(self, obs) -> Any: ...
        def get_policy_outputs(self, obs) -> Tuple[Any]: ...
    __doc__: str
    actor: Union[OnPolicySharedActorCritic.BoxActor, OnPolicySharedActorCritic.DiscreteActor, OnPolicySharedActorCritic.MultiBinaryActor]
    aux_critic: Any
    critic: Any
    dist: None
    encoder: None
    def __init__(self, action_shape: tuple, action_type: str, feature_dim: int, hidden_dim: int, aux_critic: bool = ...) -> None: ...
    def forward(self, obs) -> Any: ...
    def get_action_and_value(self, obs, actions = ...) -> tuple: ...
    def get_det_action(self, obs) -> Any: ...
    def get_policy_outputs(self, obs) -> Any: ...
    def get_probs_and_aux_value(self, obs) -> tuple: ...
    def get_value(self, obs) -> Any: ...
