
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-04T10:41:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "07c46d9d2568d029b15d99b0f0cdffcd1595dc09",
 "version": "0.9.106"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
