
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-03T09:07:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d9ed3048eb99d09715d3f99a5e809168c172bc7",
 "version": "2.12.1b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
