
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-04T15:00:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2dbdf53ffbd78a21e6c249512675bad3f1a21865",
 "version": "2.12.1b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
