
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-05T13:34:51+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "2161a2d2cb460fa4501fef9f07d2188b338ff3d2",
 "version": "1.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
