
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-05T10:20:08-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0eebc4c6b7c0ed3df19ed18df3ab6887615d09e",
 "version": "1.0.4.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
