# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfx/orchestration/experimental/centralized_kubernetes_orchestrator/service/proto/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tfx.proto.orchestration import pipeline_pb2 as tfx_dot_proto_dot_orchestration_dot_pipeline__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tfx/orchestration/experimental/centralized_kubernetes_orchestrator/service/proto/service.proto',
  package='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n^tfx/orchestration/experimental/centralized_kubernetes_orchestrator/service/proto/service.proto\x12Jtfx.orchestration.experimental.centralized_kubernetes_orchestrator.service\x1a&tfx/proto/orchestration/pipeline.proto\"\x1a\n\x0b\x45\x63hoRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1b\n\x0c\x45\x63hoResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"E\n\x14StartPipelineRequest\x12-\n\x08pipeline\x18\x01 \x01(\x0b\x32\x1b.tfx.orchestration.Pipeline\"\x17\n\x15StartPipelineResponse\"0\n\x13StopPipelineRequest\x12\x13\n\x0bpipeline_id\x18\x01 \x01(\tJ\x04\x08\x02\x10\x03\"\x16\n\x14StopPipelineResponse2\x85\x05\n\x16KubernetesOrchestrator\x12\xbb\x01\n\x04\x45\x63ho\x12W.tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.EchoRequest\x1aX.tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.EchoResponse\"\x00\x12\xd6\x01\n\rStartPipeline\x12`.tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StartPipelineRequest\x1a\x61.tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StartPipelineResponse\"\x00\x12\xd3\x01\n\x0cStopPipeline\x12_.tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StopPipelineRequest\x1a`.tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StopPipelineResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[tfx_dot_proto_dot_orchestration_dot_pipeline__pb2.DESCRIPTOR,])




_ECHOREQUEST = _descriptor.Descriptor(
  name='EchoRequest',
  full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.EchoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.EchoRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=240,
)


_ECHORESPONSE = _descriptor.Descriptor(
  name='EchoResponse',
  full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.EchoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.EchoResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=269,
)


_STARTPIPELINEREQUEST = _descriptor.Descriptor(
  name='StartPipelineRequest',
  full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StartPipelineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pipeline', full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StartPipelineRequest.pipeline', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=340,
)


_STARTPIPELINERESPONSE = _descriptor.Descriptor(
  name='StartPipelineResponse',
  full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StartPipelineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=365,
)


_STOPPIPELINEREQUEST = _descriptor.Descriptor(
  name='StopPipelineRequest',
  full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StopPipelineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pipeline_id', full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StopPipelineRequest.pipeline_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=415,
)


_STOPPIPELINERESPONSE = _descriptor.Descriptor(
  name='StopPipelineResponse',
  full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StopPipelineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=439,
)

_STARTPIPELINEREQUEST.fields_by_name['pipeline'].message_type = tfx_dot_proto_dot_orchestration_dot_pipeline__pb2._PIPELINE
DESCRIPTOR.message_types_by_name['EchoRequest'] = _ECHOREQUEST
DESCRIPTOR.message_types_by_name['EchoResponse'] = _ECHORESPONSE
DESCRIPTOR.message_types_by_name['StartPipelineRequest'] = _STARTPIPELINEREQUEST
DESCRIPTOR.message_types_by_name['StartPipelineResponse'] = _STARTPIPELINERESPONSE
DESCRIPTOR.message_types_by_name['StopPipelineRequest'] = _STOPPIPELINEREQUEST
DESCRIPTOR.message_types_by_name['StopPipelineResponse'] = _STOPPIPELINERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EchoRequest = _reflection.GeneratedProtocolMessageType('EchoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ECHOREQUEST,
  '__module__' : 'tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.EchoRequest)
  })
_sym_db.RegisterMessage(EchoRequest)

EchoResponse = _reflection.GeneratedProtocolMessageType('EchoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ECHORESPONSE,
  '__module__' : 'tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.EchoResponse)
  })
_sym_db.RegisterMessage(EchoResponse)

StartPipelineRequest = _reflection.GeneratedProtocolMessageType('StartPipelineRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTPIPELINEREQUEST,
  '__module__' : 'tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StartPipelineRequest)
  })
_sym_db.RegisterMessage(StartPipelineRequest)

StartPipelineResponse = _reflection.GeneratedProtocolMessageType('StartPipelineResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTPIPELINERESPONSE,
  '__module__' : 'tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StartPipelineResponse)
  })
_sym_db.RegisterMessage(StartPipelineResponse)

StopPipelineRequest = _reflection.GeneratedProtocolMessageType('StopPipelineRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPPIPELINEREQUEST,
  '__module__' : 'tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StopPipelineRequest)
  })
_sym_db.RegisterMessage(StopPipelineRequest)

StopPipelineResponse = _reflection.GeneratedProtocolMessageType('StopPipelineResponse', (_message.Message,), {
  'DESCRIPTOR' : _STOPPIPELINERESPONSE,
  '__module__' : 'tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.proto.service_pb2'
  # @@protoc_insertion_point(class_scope:tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.StopPipelineResponse)
  })
_sym_db.RegisterMessage(StopPipelineResponse)



_KUBERNETESORCHESTRATOR = _descriptor.ServiceDescriptor(
  name='KubernetesOrchestrator',
  full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.KubernetesOrchestrator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=442,
  serialized_end=1087,
  methods=[
  _descriptor.MethodDescriptor(
    name='Echo',
    full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.KubernetesOrchestrator.Echo',
    index=0,
    containing_service=None,
    input_type=_ECHOREQUEST,
    output_type=_ECHORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StartPipeline',
    full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.KubernetesOrchestrator.StartPipeline',
    index=1,
    containing_service=None,
    input_type=_STARTPIPELINEREQUEST,
    output_type=_STARTPIPELINERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopPipeline',
    full_name='tfx.orchestration.experimental.centralized_kubernetes_orchestrator.service.KubernetesOrchestrator.StopPipeline',
    index=2,
    containing_service=None,
    input_type=_STOPPIPELINEREQUEST,
    output_type=_STOPPIPELINERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KUBERNETESORCHESTRATOR)

DESCRIPTOR.services_by_name['KubernetesOrchestrator'] = _KUBERNETESORCHESTRATOR

# @@protoc_insertion_point(module_scope)
