
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-05T14:31:22+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d5bd14514d776ee3a1995fef263ed7befdb3fb9",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
