# coding: utf-8
# Generated by setup.py for PyCBC on 2023-05-02 09:24:14 +0000.

version = '2.1.2'
date = '2023-04-28 10:05:35 +0000'
release = True
last_release = '2.2.0'

git_hash = '57667cd1f273a7ed6a2f7b6d8ba8a0bfb9e95c1e'
git_branch = 'None'
git_tag = 'v2.1.2'
git_author = 'Tito Dal Canton <tito.dalcanton@ijclab.in2p3.fr>'
git_committer = 'Tito Dal Canton <tito@dalcanton.it>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Unknown User <>'
git_build_date = '2023-05-02 09:24:14 +0000'
git_verbose_msg = """Version: 2.1.2
Branch: None
Tag: v2.1.2
Id: 57667cd1f273a7ed6a2f7b6d8ba8a0bfb9e95c1e
Builder: Unknown User <>
Build date: 2023-05-02 09:24:14 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
