from setuptools import setup, find_packages

setup(
    name="utilspggmdatalab",
    version="0.3",
    packages=find_packages(),
    install_requires=[
        "azure-core==1.26.4",
        "azure-data-tables==12.4.2",
        "azure-functions==1.13.3",
        "azure-storage-blob==12.16.0",
        "azure-storage-queue==12.6.0",
        "certifi==2022.12.7",
        "cffi==1.15.1",
        "charset-normalizer==3.1.0",
        "cryptography==40.0.2",
        "idna==3.4",
        "isodate==0.6.1",
        "langdetect==1.0.9",
        "multidict==6.0.4",
        "numpy==1.24.3",
        "pandas==2.0.1",
        "pycparser==2.21",
        "pyodbc==4.0.39",
        "python-dateutil==2.8.2",
        "python-dotenv==1.0.0",
        "pytz==2023.3",
        "requests==2.28.2",
        "six==1.16.0",
        "typing_extensions==4.5.0",
        "tzdata==2023.3",
        "urllib3==1.26.15",
        "yarl==1.9.2"
    ],
    author="Dominique Stoverink",
    author_email="dominique.stoverink@pggm.nl",
    description="A toolkit module for the Mimir app created in Innovation Data Lab",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/PGGM-Innovatie/utilspggmdatalab",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11"
    ],
)
