
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-05T08:08:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd7cfeb468ef7a7ab21c5154743a6056085c3629",
 "version": "2.12.1b4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
