# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from moneykit.paths.auth_introspect.get import InstrospectClient
from moneykit.paths.auth_token.post import GenerateAccessToken
from moneykit.paths.well_known_jwks_json.get import GetWellKnownJwks


class AccessTokenApi(
    GenerateAccessToken,
    GetWellKnownJwks,
    InstrospectClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
