VERSION_YEAR = 2023
VERSION_MONTH = int('05')
VERSION_DAY = int('02')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('42')
MAJOR_VERSION = 0
MINOR_VERSION = 7
PATCH_VERSION = 202305021042
version_date = '2023/05/02 10:42'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
