
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-28T14:57:23+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbace8de2b4e95ac3b4dbf44ac005bc6458249f6",
 "version": "2.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
