
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-24T19:44:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9fd3af71a9cf455f408dbb32afe4c175d9128432",
 "version": "2.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
