
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-03T21:19:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "04d4f7da0571fcdf2fd802e5eb2925417b81e34c",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
