"""__init__.py"""


from mastapy._internal.dummy_base_class_importer import _DummyBaseClassImport


with _DummyBaseClassImport():
    from ._993 import AddendumModificationDistributionRule
    from ._994 import BacklashSpecification
    from ._995 import BasicRackProfiles
    from ._996 import CaseHardeningProperties
    from ._997 import CreateNewSuitableCutterOption
    from ._998 import CrossedAxisCylindricalGearPair
    from ._999 import CrossedAxisCylindricalGearPairLineContact
    from ._1000 import CrossedAxisCylindricalGearPairPointContact
    from ._1001 import CylindricalGearAbstractRack
    from ._1002 import CylindricalGearAbstractRackFlank
    from ._1003 import CylindricalGearBasicRack
    from ._1004 import CylindricalGearBasicRackFlank
    from ._1005 import CylindricalGearCuttingOptions
    from ._1006 import CylindricalGearDefaults
    from ._1007 import CylindricalGearDesign
    from ._1008 import CylindricalGearDesignConstraint
    from ._1009 import CylindricalGearDesignConstraints
    from ._1010 import CylindricalGearDesignConstraintsDatabase
    from ._1011 import CylindricalGearDesignConstraintSettings
    from ._1012 import CylindricalGearFlankDesign
    from ._1013 import CylindricalGearMeshDesign
    from ._1014 import CylindricalGearMeshFlankDesign
    from ._1015 import CylindricalGearMicroGeometrySettings
    from ._1016 import CylindricalGearMicroGeometrySettingsDatabase
    from ._1017 import CylindricalGearMicroGeometrySettingsItem
    from ._1018 import CylindricalGearPinionTypeCutter
    from ._1019 import CylindricalGearPinionTypeCutterFlank
    from ._1020 import CylindricalGearProfileMeasurement
    from ._1021 import CylindricalGearProfileMeasurementType
    from ._1022 import CylindricalGearProfileModifications
    from ._1023 import CylindricalGearSetDesign
    from ._1024 import CylindricalGearSetFlankDesign
    from ._1025 import CylindricalGearSetMacroGeometryOptimiser
    from ._1026 import CylindricalGearSetManufacturingConfigurationSelection
    from ._1027 import CylindricalGearSetMicroGeometrySettings
    from ._1028 import CylindricalGearTableMGItemDetail
    from ._1029 import CylindricalGearTableWithMGCharts
    from ._1030 import CylindricalGearToothThicknessSpecification
    from ._1031 import CylindricalMeshAngularBacklash
    from ._1032 import CylindricalMeshedGear
    from ._1033 import CylindricalMeshedGearFlank
    from ._1034 import CylindricalMeshLinearBacklashSpecification
    from ._1035 import CylindricalPlanetaryGearSetDesign
    from ._1036 import CylindricalPlanetGearDesign
    from ._1037 import DIN3967AllowanceSeries
    from ._1038 import DIN3967ToleranceSeries
    from ._1039 import DoubleAxisScaleAndRange
    from ._1040 import FinishToothThicknessDesignSpecification
    from ._1041 import GearFitSystems
    from ._1042 import GearManufacturingConfigSetupViewModel
    from ._1043 import GearSetManufacturingConfigurationSetup
    from ._1044 import GeometrySpecificationType
    from ._1045 import HardenedMaterialProperties
    from ._1046 import HardnessProfileCalculationMethod
    from ._1047 import HeatTreatmentType
    from ._1048 import ISO6336Geometry
    from ._1049 import ISO6336GeometryBase
    from ._1050 import ISO6336GeometryForShapedGears
    from ._1051 import ISO6336GeometryManufactured
    from ._1052 import LinearBacklashSepcification
    from ._1053 import LTCALoadCaseModifiableSettings
    from ._1054 import LtcaSettings
    from ._1055 import MicroGeometryConvention
    from ._1056 import MicroGeometryProfileConvention
    from ._1057 import Micropitting
    from ._1058 import NamedPlanetAssemblyIndex
    from ._1059 import NamedPlanetSideBandAmplitudeFactor
    from ._1060 import ReadonlyToothThicknessSpecification
    from ._1061 import RelativeMeasurementViewModel
    from ._1062 import RelativeValuesSpecification
    from ._1063 import RootStressSurfaceChartOption
    from ._1064 import Scuffing
    from ._1065 import ScuffingCoefficientOfFrictionMethods
    from ._1066 import ScuffingTemperatureMethodsAGMA
    from ._1067 import ScuffingTemperatureMethodsISO
    from ._1068 import ShaperEdgeTypes
    from ._1069 import SpurGearLoadSharingCodes
    from ._1070 import StandardRack
    from ._1071 import StandardRackFlank
    from ._1072 import SurfaceRoughness
    from ._1073 import ThicknessType
    from ._1074 import TiffAnalysisSettings
    from ._1075 import TipAlterationCoefficientMethod
    from ._1076 import TolerancedMetalMeasurements
    from ._1077 import TolerancedValueSpecification
    from ._1078 import ToothFlankFractureAnalysisSettings
    from ._1079 import ToothThicknessSpecification
    from ._1080 import ToothThicknessSpecificationBase
    from ._1081 import TypeOfMechanismHousing
    from ._1082 import Usage
