# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import uuid  # noqa: F401
from datetime import date, datetime  # noqa: F401

import frozendict  # noqa: F401
import typing_extensions  # noqa: F401

from moneykit import schemas  # noqa: F401


class IdentityResponse(schemas.DictSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    class MetaOapg:
        required = {
            "link",
            "accounts",
        }

        class properties:
            class accounts(schemas.ListSchema):
                class MetaOapg:
                    @staticmethod
                    def items() -> typing.Type["AccountIdentity"]:
                        return AccountIdentity

                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple["AccountIdentity"], typing.List["AccountIdentity"]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> "accounts":
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )

                def __getitem__(self, i: int) -> "AccountIdentity":
                    return super().__getitem__(i)

            @staticmethod
            def link() -> typing.Type["LinkCommon"]:
                return LinkCommon

            __annotations__ = {
                "accounts": accounts,
                "link": link,
            }

    link: "LinkCommon"
    accounts: MetaOapg.properties.accounts

    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["accounts"]) -> MetaOapg.properties.accounts:
        ...

    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["link"]) -> "LinkCommon":
        ...

    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema:
        ...

    def __getitem__(
        self,
        name: typing.Union[
            typing_extensions.Literal[
                "accounts",
                "link",
            ],
            str,
        ],
    ):
        # dict_instance[name] accessor
        return super().__getitem__(name)

    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["accounts"]) -> MetaOapg.properties.accounts:
        ...

    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["link"]) -> "LinkCommon":
        ...

    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]:
        ...

    def get_item_oapg(
        self,
        name: typing.Union[
            typing_extensions.Literal[
                "accounts",
                "link",
            ],
            str,
        ],
    ):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[
            dict,
            frozendict.frozendict,
        ],
        link: "LinkCommon",
        accounts: typing.Union[
            MetaOapg.properties.accounts,
            list,
            tuple,
        ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[
            schemas.AnyTypeSchema,
            dict,
            frozendict.frozendict,
            str,
            date,
            datetime,
            uuid.UUID,
            int,
            float,
            decimal.Decimal,
            None,
            list,
            tuple,
            bytes,
        ],
    ) -> "IdentityResponse":
        return super().__new__(
            cls,
            *_args,
            link=link,
            accounts=accounts,
            _configuration=_configuration,
            **kwargs,
        )


from moneykit.model.account_identity import AccountIdentity
from moneykit.model.link_common import LinkCommon
