# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import uuid  # noqa: F401
from datetime import date, datetime  # noqa: F401

import frozendict  # noqa: F401
import typing_extensions  # noqa: F401

from moneykit import schemas  # noqa: F401


class LinkSessionErrorInvalidTokenExchange(schemas.DictSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    class MetaOapg:
        required = {
            "error_message",
        }

        class properties:
            error_message = schemas.StrSchema

            class error_code(schemas.EnumBase, schemas.StrSchema):
                class MetaOapg:
                    enum_value_to_name = {
                        "link_session_error.invalid_token_exchange": "LINK_SESSION_ERROR_INVALID_TOKEN_EXCHANGE",
                    }

                @schemas.classproperty
                def LINK_SESSION_ERROR_INVALID_TOKEN_EXCHANGE(cls):
                    return cls("link_session_error.invalid_token_exchange")

            class documentation_url(schemas.StrBase, schemas.NoneBase, schemas.Schema, schemas.NoneStrMixin):
                def __new__(
                    cls,
                    *_args: typing.Union[
                        None,
                        str,
                    ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> "documentation_url":
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )

            __annotations__ = {
                "error_message": error_message,
                "error_code": error_code,
                "documentation_url": documentation_url,
            }

    error_message: MetaOapg.properties.error_message

    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error_message"]) -> MetaOapg.properties.error_message:
        ...

    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error_code"]) -> MetaOapg.properties.error_code:
        ...

    @typing.overload
    def __getitem__(
        self, name: typing_extensions.Literal["documentation_url"]
    ) -> MetaOapg.properties.documentation_url:
        ...

    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema:
        ...

    def __getitem__(
        self,
        name: typing.Union[
            typing_extensions.Literal[
                "error_message",
                "error_code",
                "documentation_url",
            ],
            str,
        ],
    ):
        # dict_instance[name] accessor
        return super().__getitem__(name)

    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error_message"]) -> MetaOapg.properties.error_message:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["error_code"]
    ) -> typing.Union[MetaOapg.properties.error_code, schemas.Unset]:
        ...

    @typing.overload
    def get_item_oapg(
        self, name: typing_extensions.Literal["documentation_url"]
    ) -> typing.Union[MetaOapg.properties.documentation_url, schemas.Unset]:
        ...

    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]:
        ...

    def get_item_oapg(
        self,
        name: typing.Union[
            typing_extensions.Literal[
                "error_message",
                "error_code",
                "documentation_url",
            ],
            str,
        ],
    ):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[
            dict,
            frozendict.frozendict,
        ],
        error_message: typing.Union[
            MetaOapg.properties.error_message,
            str,
        ],
        error_code: typing.Union[MetaOapg.properties.error_code, str, schemas.Unset] = schemas.unset,
        documentation_url: typing.Union[
            MetaOapg.properties.documentation_url, None, str, schemas.Unset
        ] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[
            schemas.AnyTypeSchema,
            dict,
            frozendict.frozendict,
            str,
            date,
            datetime,
            uuid.UUID,
            int,
            float,
            decimal.Decimal,
            None,
            list,
            tuple,
            bytes,
        ],
    ) -> "LinkSessionErrorInvalidTokenExchange":
        return super().__new__(
            cls,
            *_args,
            error_message=error_message,
            error_code=error_code,
            documentation_url=documentation_url,
            _configuration=_configuration,
            **kwargs,
        )
