# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from moneykit.paths.link_session.post import CreateLinkSession
from moneykit.paths.link_session_exchange_token.post import ExchangeToken


class LinkSessionApi(
    CreateLinkSession,
    ExchangeToken,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
