# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from moneykit.paths.links_id.delete import Disconnect
from moneykit.paths.links_id.get import GetLink
from moneykit.paths.links_id.patch import UpdateLink
from moneykit.paths.users_id_links.get import GetUserLinks


class LinksApi(
    Disconnect,
    GetLink,
    GetUserLinks,
    UpdateLink,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
