# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

from moneykit.paths.users_id_accounts.get import GetUserAccounts
from moneykit.paths.users_id_links.get import GetUserLinks
from moneykit.paths.users_id_transactions.get import GetUserTransactions


class UsersApi(
    GetUserAccounts,
    GetUserLinks,
    GetUserTransactions,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    pass
