
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-03T17:22:15-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac9fb07493cc8d5cacf8a7c41cfdf0de565a1d87",
 "version": "0.29.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
