
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-02T10:34:31+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cdfa1612d5f78bfb8d570fad88a0b12dca0a6e8",
 "version": "0.29.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
