# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfx/proto/distribution_validator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow_metadata.proto.v0 import path_pb2 as tensorflow__metadata_dot_proto_dot_v0_dot_path__pb2
from tensorflow_metadata.proto.v0 import schema_pb2 as tensorflow__metadata_dot_proto_dot_v0_dot_schema__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tfx/proto/distribution_validator.proto',
  package='tfx.components.distribution_validator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&tfx/proto/distribution_validator.proto\x12%tfx.components.distribution_validator\x1a\'tensorflow_metadata/proto/v0/path.proto\x1a)tensorflow_metadata/proto/v0/schema.proto\"\x8b\x01\n\x11\x46\x65\x61tureComparator\x12*\n\x04path\x18\x01 \x01(\x0b\x32\x1c.tensorflow.metadata.v0.Path\x12J\n\x17\x64istribution_comparator\x18\x02 \x01(\x0b\x32).tensorflow.metadata.v0.FeatureComparator\"\xbb\x02\n\x1b\x44istributionValidatorConfig\x12n\n\x14\x64\x65\x66\x61ult_slice_config\x18\x01 \x01(\x0b\x32P.tfx.components.distribution_validator.DistributionValidatorConfig.DatasetConfig\x1a\xab\x01\n\rDatasetConfig\x12I\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32\x38.tfx.components.distribution_validator.FeatureComparator\x12O\n\x17num_examples_comparator\x18\x02 \x01(\x0b\x32..tensorflow.metadata.v0.NumericValueComparatorb\x06proto3')
  ,
  dependencies=[tensorflow__metadata_dot_proto_dot_v0_dot_path__pb2.DESCRIPTOR,tensorflow__metadata_dot_proto_dot_v0_dot_schema__pb2.DESCRIPTOR,])




_FEATURECOMPARATOR = _descriptor.Descriptor(
  name='FeatureComparator',
  full_name='tfx.components.distribution_validator.FeatureComparator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='tfx.components.distribution_validator.FeatureComparator.path', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distribution_comparator', full_name='tfx.components.distribution_validator.FeatureComparator.distribution_comparator', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=305,
)


_DISTRIBUTIONVALIDATORCONFIG_DATASETCONFIG = _descriptor.Descriptor(
  name='DatasetConfig',
  full_name='tfx.components.distribution_validator.DistributionValidatorConfig.DatasetConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='tfx.components.distribution_validator.DistributionValidatorConfig.DatasetConfig.feature', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_examples_comparator', full_name='tfx.components.distribution_validator.DistributionValidatorConfig.DatasetConfig.num_examples_comparator', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=623,
)

_DISTRIBUTIONVALIDATORCONFIG = _descriptor.Descriptor(
  name='DistributionValidatorConfig',
  full_name='tfx.components.distribution_validator.DistributionValidatorConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='default_slice_config', full_name='tfx.components.distribution_validator.DistributionValidatorConfig.default_slice_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DISTRIBUTIONVALIDATORCONFIG_DATASETCONFIG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=623,
)

_FEATURECOMPARATOR.fields_by_name['path'].message_type = tensorflow__metadata_dot_proto_dot_v0_dot_path__pb2._PATH
_FEATURECOMPARATOR.fields_by_name['distribution_comparator'].message_type = tensorflow__metadata_dot_proto_dot_v0_dot_schema__pb2._FEATURECOMPARATOR
_DISTRIBUTIONVALIDATORCONFIG_DATASETCONFIG.fields_by_name['feature'].message_type = _FEATURECOMPARATOR
_DISTRIBUTIONVALIDATORCONFIG_DATASETCONFIG.fields_by_name['num_examples_comparator'].message_type = tensorflow__metadata_dot_proto_dot_v0_dot_schema__pb2._NUMERICVALUECOMPARATOR
_DISTRIBUTIONVALIDATORCONFIG_DATASETCONFIG.containing_type = _DISTRIBUTIONVALIDATORCONFIG
_DISTRIBUTIONVALIDATORCONFIG.fields_by_name['default_slice_config'].message_type = _DISTRIBUTIONVALIDATORCONFIG_DATASETCONFIG
DESCRIPTOR.message_types_by_name['FeatureComparator'] = _FEATURECOMPARATOR
DESCRIPTOR.message_types_by_name['DistributionValidatorConfig'] = _DISTRIBUTIONVALIDATORCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureComparator = _reflection.GeneratedProtocolMessageType('FeatureComparator', (_message.Message,), {
  'DESCRIPTOR' : _FEATURECOMPARATOR,
  '__module__' : 'tfx.proto.distribution_validator_pb2'
  # @@protoc_insertion_point(class_scope:tfx.components.distribution_validator.FeatureComparator)
  })
_sym_db.RegisterMessage(FeatureComparator)

DistributionValidatorConfig = _reflection.GeneratedProtocolMessageType('DistributionValidatorConfig', (_message.Message,), {

  'DatasetConfig' : _reflection.GeneratedProtocolMessageType('DatasetConfig', (_message.Message,), {
    'DESCRIPTOR' : _DISTRIBUTIONVALIDATORCONFIG_DATASETCONFIG,
    '__module__' : 'tfx.proto.distribution_validator_pb2'
    # @@protoc_insertion_point(class_scope:tfx.components.distribution_validator.DistributionValidatorConfig.DatasetConfig)
    })
  ,
  'DESCRIPTOR' : _DISTRIBUTIONVALIDATORCONFIG,
  '__module__' : 'tfx.proto.distribution_validator_pb2'
  # @@protoc_insertion_point(class_scope:tfx.components.distribution_validator.DistributionValidatorConfig)
  })
_sym_db.RegisterMessage(DistributionValidatorConfig)
_sym_db.RegisterMessage(DistributionValidatorConfig.DatasetConfig)


# @@protoc_insertion_point(module_scope)
