# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfx/proto/orchestration/execution_watcher.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ml_metadata.proto import metadata_store_pb2 as ml__metadata_dot_proto_dot_metadata__store__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tfx/proto/orchestration/execution_watcher.proto',
  package='tfx.orchestration',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/tfx/proto/orchestration/execution_watcher.proto\x12\x11tfx.orchestration\x1a&ml_metadata/proto/metadata_store.proto\"\xc3\x01\n\x1aUpdateExecutionInfoRequest\x12K\n\x07updates\x18\x01 \x03(\x0b\x32:.tfx.orchestration.UpdateExecutionInfoRequest.UpdatesEntry\x12\x14\n\x0c\x65xecution_id\x18\x02 \x01(\x03\x1a\x42\n\x0cUpdatesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.ml_metadata.Value:\x02\x38\x01\"\x1d\n\x1bUpdateExecutionInfoResponse2\x91\x01\n\x17\x45xecutionWatcherService\x12v\n\x13UpdateExecutionInfo\x12-.tfx.orchestration.UpdateExecutionInfoRequest\x1a..tfx.orchestration.UpdateExecutionInfoResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[ml__metadata_dot_proto_dot_metadata__store__pb2.DESCRIPTOR,])




_UPDATEEXECUTIONINFOREQUEST_UPDATESENTRY = _descriptor.Descriptor(
  name='UpdatesEntry',
  full_name='tfx.orchestration.UpdateExecutionInfoRequest.UpdatesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tfx.orchestration.UpdateExecutionInfoRequest.UpdatesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='tfx.orchestration.UpdateExecutionInfoRequest.UpdatesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=306,
)

_UPDATEEXECUTIONINFOREQUEST = _descriptor.Descriptor(
  name='UpdateExecutionInfoRequest',
  full_name='tfx.orchestration.UpdateExecutionInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='updates', full_name='tfx.orchestration.UpdateExecutionInfoRequest.updates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='execution_id', full_name='tfx.orchestration.UpdateExecutionInfoRequest.execution_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_UPDATEEXECUTIONINFOREQUEST_UPDATESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=306,
)


_UPDATEEXECUTIONINFORESPONSE = _descriptor.Descriptor(
  name='UpdateExecutionInfoResponse',
  full_name='tfx.orchestration.UpdateExecutionInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=337,
)

_UPDATEEXECUTIONINFOREQUEST_UPDATESENTRY.fields_by_name['value'].message_type = ml__metadata_dot_proto_dot_metadata__store__pb2._VALUE
_UPDATEEXECUTIONINFOREQUEST_UPDATESENTRY.containing_type = _UPDATEEXECUTIONINFOREQUEST
_UPDATEEXECUTIONINFOREQUEST.fields_by_name['updates'].message_type = _UPDATEEXECUTIONINFOREQUEST_UPDATESENTRY
DESCRIPTOR.message_types_by_name['UpdateExecutionInfoRequest'] = _UPDATEEXECUTIONINFOREQUEST
DESCRIPTOR.message_types_by_name['UpdateExecutionInfoResponse'] = _UPDATEEXECUTIONINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateExecutionInfoRequest = _reflection.GeneratedProtocolMessageType('UpdateExecutionInfoRequest', (_message.Message,), {

  'UpdatesEntry' : _reflection.GeneratedProtocolMessageType('UpdatesEntry', (_message.Message,), {
    'DESCRIPTOR' : _UPDATEEXECUTIONINFOREQUEST_UPDATESENTRY,
    '__module__' : 'tfx.proto.orchestration.execution_watcher_pb2'
    # @@protoc_insertion_point(class_scope:tfx.orchestration.UpdateExecutionInfoRequest.UpdatesEntry)
    })
  ,
  'DESCRIPTOR' : _UPDATEEXECUTIONINFOREQUEST,
  '__module__' : 'tfx.proto.orchestration.execution_watcher_pb2'
  # @@protoc_insertion_point(class_scope:tfx.orchestration.UpdateExecutionInfoRequest)
  })
_sym_db.RegisterMessage(UpdateExecutionInfoRequest)
_sym_db.RegisterMessage(UpdateExecutionInfoRequest.UpdatesEntry)

UpdateExecutionInfoResponse = _reflection.GeneratedProtocolMessageType('UpdateExecutionInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEEXECUTIONINFORESPONSE,
  '__module__' : 'tfx.proto.orchestration.execution_watcher_pb2'
  # @@protoc_insertion_point(class_scope:tfx.orchestration.UpdateExecutionInfoResponse)
  })
_sym_db.RegisterMessage(UpdateExecutionInfoResponse)


_UPDATEEXECUTIONINFOREQUEST_UPDATESENTRY._options = None

_EXECUTIONWATCHERSERVICE = _descriptor.ServiceDescriptor(
  name='ExecutionWatcherService',
  full_name='tfx.orchestration.ExecutionWatcherService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=340,
  serialized_end=485,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateExecutionInfo',
    full_name='tfx.orchestration.ExecutionWatcherService.UpdateExecutionInfo',
    index=0,
    containing_service=None,
    input_type=_UPDATEEXECUTIONINFOREQUEST,
    output_type=_UPDATEEXECUTIONINFORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXECUTIONWATCHERSERVICE)

DESCRIPTOR.services_by_name['ExecutionWatcherService'] = _EXECUTIONWATCHERSERVICE

# @@protoc_insertion_point(module_scope)
