
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-06T00:29:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdaf33ab1ac9f085b24ca1684a008ead23774543",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
