# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import uuid  # noqa: F401
from datetime import date, datetime  # noqa: F401

import frozendict  # noqa: F401
import typing_extensions  # noqa: F401

from moneykit import schemas  # noqa: F401

class Currency(schemas.EnumBase, schemas.StrSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
        Ref: https://openapi-generator.tech

        Do not edit the class manually.

        ISO 4217 currency.  Its enumerants are ISO 4217 currencies except for
    some special currencies like ```XXX``.  Enumerants names are lowercase
    cureency code e.g. :attr:`Currency.eur`, :attr:`Currency.usd`.
    """

    @schemas.classproperty
    def AFN(cls):
        return cls("AFN")
    @schemas.classproperty
    def EUR(cls):
        return cls("EUR")
    @schemas.classproperty
    def ALL(cls):
        return cls("ALL")
    @schemas.classproperty
    def DZD(cls):
        return cls("DZD")
    @schemas.classproperty
    def USD(cls):
        return cls("USD")
    @schemas.classproperty
    def AOA(cls):
        return cls("AOA")
    @schemas.classproperty
    def XCD(cls):
        return cls("XCD")
    @schemas.classproperty
    def ARS(cls):
        return cls("ARS")
    @schemas.classproperty
    def AMD(cls):
        return cls("AMD")
    @schemas.classproperty
    def AWG(cls):
        return cls("AWG")
    @schemas.classproperty
    def AUD(cls):
        return cls("AUD")
    @schemas.classproperty
    def AZN(cls):
        return cls("AZN")
    @schemas.classproperty
    def BSD(cls):
        return cls("BSD")
    @schemas.classproperty
    def BHD(cls):
        return cls("BHD")
    @schemas.classproperty
    def BDT(cls):
        return cls("BDT")
    @schemas.classproperty
    def BBD(cls):
        return cls("BBD")
    @schemas.classproperty
    def BYN(cls):
        return cls("BYN")
    @schemas.classproperty
    def BZD(cls):
        return cls("BZD")
    @schemas.classproperty
    def XOF(cls):
        return cls("XOF")
    @schemas.classproperty
    def BMD(cls):
        return cls("BMD")
    @schemas.classproperty
    def INR(cls):
        return cls("INR")
    @schemas.classproperty
    def BTN(cls):
        return cls("BTN")
    @schemas.classproperty
    def BOB(cls):
        return cls("BOB")
    @schemas.classproperty
    def BOV(cls):
        return cls("BOV")
    @schemas.classproperty
    def BAM(cls):
        return cls("BAM")
    @schemas.classproperty
    def BWP(cls):
        return cls("BWP")
    @schemas.classproperty
    def NOK(cls):
        return cls("NOK")
    @schemas.classproperty
    def BRL(cls):
        return cls("BRL")
    @schemas.classproperty
    def BND(cls):
        return cls("BND")
    @schemas.classproperty
    def BGN(cls):
        return cls("BGN")
    @schemas.classproperty
    def BIF(cls):
        return cls("BIF")
    @schemas.classproperty
    def CVE(cls):
        return cls("CVE")
    @schemas.classproperty
    def KHR(cls):
        return cls("KHR")
    @schemas.classproperty
    def XAF(cls):
        return cls("XAF")
    @schemas.classproperty
    def CAD(cls):
        return cls("CAD")
    @schemas.classproperty
    def KYD(cls):
        return cls("KYD")
    @schemas.classproperty
    def CLP(cls):
        return cls("CLP")
    @schemas.classproperty
    def CLF(cls):
        return cls("CLF")
    @schemas.classproperty
    def CNY(cls):
        return cls("CNY")
    @schemas.classproperty
    def COP(cls):
        return cls("COP")
    @schemas.classproperty
    def COU(cls):
        return cls("COU")
    @schemas.classproperty
    def KMF(cls):
        return cls("KMF")
    @schemas.classproperty
    def CDF(cls):
        return cls("CDF")
    @schemas.classproperty
    def NZD(cls):
        return cls("NZD")
    @schemas.classproperty
    def CRC(cls):
        return cls("CRC")
    @schemas.classproperty
    def HRK(cls):
        return cls("HRK")
    @schemas.classproperty
    def CUP(cls):
        return cls("CUP")
    @schemas.classproperty
    def CUC(cls):
        return cls("CUC")
    @schemas.classproperty
    def ANG(cls):
        return cls("ANG")
    @schemas.classproperty
    def CZK(cls):
        return cls("CZK")
    @schemas.classproperty
    def DKK(cls):
        return cls("DKK")
    @schemas.classproperty
    def DJF(cls):
        return cls("DJF")
    @schemas.classproperty
    def DOP(cls):
        return cls("DOP")
    @schemas.classproperty
    def EGP(cls):
        return cls("EGP")
    @schemas.classproperty
    def SVC(cls):
        return cls("SVC")
    @schemas.classproperty
    def ERN(cls):
        return cls("ERN")
    @schemas.classproperty
    def SZL(cls):
        return cls("SZL")
    @schemas.classproperty
    def ETB(cls):
        return cls("ETB")
    @schemas.classproperty
    def FKP(cls):
        return cls("FKP")
    @schemas.classproperty
    def FJD(cls):
        return cls("FJD")
    @schemas.classproperty
    def XPF(cls):
        return cls("XPF")
    @schemas.classproperty
    def GMD(cls):
        return cls("GMD")
    @schemas.classproperty
    def GEL(cls):
        return cls("GEL")
    @schemas.classproperty
    def GHS(cls):
        return cls("GHS")
    @schemas.classproperty
    def GIP(cls):
        return cls("GIP")
    @schemas.classproperty
    def GTQ(cls):
        return cls("GTQ")
    @schemas.classproperty
    def GBP(cls):
        return cls("GBP")
    @schemas.classproperty
    def GNF(cls):
        return cls("GNF")
    @schemas.classproperty
    def GYD(cls):
        return cls("GYD")
    @schemas.classproperty
    def HTG(cls):
        return cls("HTG")
    @schemas.classproperty
    def HNL(cls):
        return cls("HNL")
    @schemas.classproperty
    def HKD(cls):
        return cls("HKD")
    @schemas.classproperty
    def HUF(cls):
        return cls("HUF")
    @schemas.classproperty
    def ISK(cls):
        return cls("ISK")
    @schemas.classproperty
    def IDR(cls):
        return cls("IDR")
    @schemas.classproperty
    def XDR(cls):
        return cls("XDR")
    @schemas.classproperty
    def IRR(cls):
        return cls("IRR")
    @schemas.classproperty
    def IQD(cls):
        return cls("IQD")
    @schemas.classproperty
    def ILS(cls):
        return cls("ILS")
    @schemas.classproperty
    def JMD(cls):
        return cls("JMD")
    @schemas.classproperty
    def JPY(cls):
        return cls("JPY")
    @schemas.classproperty
    def JOD(cls):
        return cls("JOD")
    @schemas.classproperty
    def KZT(cls):
        return cls("KZT")
    @schemas.classproperty
    def KES(cls):
        return cls("KES")
    @schemas.classproperty
    def KPW(cls):
        return cls("KPW")
    @schemas.classproperty
    def KRW(cls):
        return cls("KRW")
    @schemas.classproperty
    def KWD(cls):
        return cls("KWD")
    @schemas.classproperty
    def KGS(cls):
        return cls("KGS")
    @schemas.classproperty
    def LAK(cls):
        return cls("LAK")
    @schemas.classproperty
    def LBP(cls):
        return cls("LBP")
    @schemas.classproperty
    def LSL(cls):
        return cls("LSL")
    @schemas.classproperty
    def ZAR(cls):
        return cls("ZAR")
    @schemas.classproperty
    def LRD(cls):
        return cls("LRD")
    @schemas.classproperty
    def LYD(cls):
        return cls("LYD")
    @schemas.classproperty
    def CHF(cls):
        return cls("CHF")
    @schemas.classproperty
    def MOP(cls):
        return cls("MOP")
    @schemas.classproperty
    def MKD(cls):
        return cls("MKD")
    @schemas.classproperty
    def MGA(cls):
        return cls("MGA")
    @schemas.classproperty
    def MWK(cls):
        return cls("MWK")
    @schemas.classproperty
    def MYR(cls):
        return cls("MYR")
    @schemas.classproperty
    def MVR(cls):
        return cls("MVR")
    @schemas.classproperty
    def MRU(cls):
        return cls("MRU")
    @schemas.classproperty
    def MUR(cls):
        return cls("MUR")
    @schemas.classproperty
    def XUA(cls):
        return cls("XUA")
    @schemas.classproperty
    def MXN(cls):
        return cls("MXN")
    @schemas.classproperty
    def MXV(cls):
        return cls("MXV")
    @schemas.classproperty
    def MDL(cls):
        return cls("MDL")
    @schemas.classproperty
    def MNT(cls):
        return cls("MNT")
    @schemas.classproperty
    def MAD(cls):
        return cls("MAD")
    @schemas.classproperty
    def MZN(cls):
        return cls("MZN")
    @schemas.classproperty
    def MMK(cls):
        return cls("MMK")
    @schemas.classproperty
    def NAD(cls):
        return cls("NAD")
    @schemas.classproperty
    def NPR(cls):
        return cls("NPR")
    @schemas.classproperty
    def NIO(cls):
        return cls("NIO")
    @schemas.classproperty
    def NGN(cls):
        return cls("NGN")
    @schemas.classproperty
    def OMR(cls):
        return cls("OMR")
    @schemas.classproperty
    def PKR(cls):
        return cls("PKR")
    @schemas.classproperty
    def PAB(cls):
        return cls("PAB")
    @schemas.classproperty
    def PGK(cls):
        return cls("PGK")
    @schemas.classproperty
    def PYG(cls):
        return cls("PYG")
    @schemas.classproperty
    def PEN(cls):
        return cls("PEN")
    @schemas.classproperty
    def PHP(cls):
        return cls("PHP")
    @schemas.classproperty
    def PLN(cls):
        return cls("PLN")
    @schemas.classproperty
    def QAR(cls):
        return cls("QAR")
    @schemas.classproperty
    def RON(cls):
        return cls("RON")
    @schemas.classproperty
    def RUB(cls):
        return cls("RUB")
    @schemas.classproperty
    def RWF(cls):
        return cls("RWF")
    @schemas.classproperty
    def SHP(cls):
        return cls("SHP")
    @schemas.classproperty
    def WST(cls):
        return cls("WST")
    @schemas.classproperty
    def STN(cls):
        return cls("STN")
    @schemas.classproperty
    def SAR(cls):
        return cls("SAR")
    @schemas.classproperty
    def RSD(cls):
        return cls("RSD")
    @schemas.classproperty
    def SCR(cls):
        return cls("SCR")
    @schemas.classproperty
    def SLL(cls):
        return cls("SLL")
    @schemas.classproperty
    def SLE(cls):
        return cls("SLE")
    @schemas.classproperty
    def SGD(cls):
        return cls("SGD")
    @schemas.classproperty
    def XSU(cls):
        return cls("XSU")
    @schemas.classproperty
    def SBD(cls):
        return cls("SBD")
    @schemas.classproperty
    def SOS(cls):
        return cls("SOS")
    @schemas.classproperty
    def SSP(cls):
        return cls("SSP")
    @schemas.classproperty
    def LKR(cls):
        return cls("LKR")
    @schemas.classproperty
    def SDG(cls):
        return cls("SDG")
    @schemas.classproperty
    def SRD(cls):
        return cls("SRD")
    @schemas.classproperty
    def SEK(cls):
        return cls("SEK")
    @schemas.classproperty
    def CHE(cls):
        return cls("CHE")
    @schemas.classproperty
    def CHW(cls):
        return cls("CHW")
    @schemas.classproperty
    def SYP(cls):
        return cls("SYP")
    @schemas.classproperty
    def TWD(cls):
        return cls("TWD")
    @schemas.classproperty
    def TJS(cls):
        return cls("TJS")
    @schemas.classproperty
    def TZS(cls):
        return cls("TZS")
    @schemas.classproperty
    def THB(cls):
        return cls("THB")
    @schemas.classproperty
    def TOP(cls):
        return cls("TOP")
    @schemas.classproperty
    def TTD(cls):
        return cls("TTD")
    @schemas.classproperty
    def TND(cls):
        return cls("TND")
    @schemas.classproperty
    def TRY(cls):
        return cls("TRY")
    @schemas.classproperty
    def TMT(cls):
        return cls("TMT")
    @schemas.classproperty
    def UGX(cls):
        return cls("UGX")
    @schemas.classproperty
    def UAH(cls):
        return cls("UAH")
    @schemas.classproperty
    def AED(cls):
        return cls("AED")
    @schemas.classproperty
    def USN(cls):
        return cls("USN")
    @schemas.classproperty
    def UYU(cls):
        return cls("UYU")
    @schemas.classproperty
    def UYI(cls):
        return cls("UYI")
    @schemas.classproperty
    def UYW(cls):
        return cls("UYW")
    @schemas.classproperty
    def UZS(cls):
        return cls("UZS")
    @schemas.classproperty
    def VUV(cls):
        return cls("VUV")
    @schemas.classproperty
    def VES(cls):
        return cls("VES")
    @schemas.classproperty
    def VED(cls):
        return cls("VED")
    @schemas.classproperty
    def VND(cls):
        return cls("VND")
    @schemas.classproperty
    def YER(cls):
        return cls("YER")
    @schemas.classproperty
    def ZMW(cls):
        return cls("ZMW")
    @schemas.classproperty
    def ZWL(cls):
        return cls("ZWL")
    @schemas.classproperty
    def XBA(cls):
        return cls("XBA")
    @schemas.classproperty
    def XBB(cls):
        return cls("XBB")
    @schemas.classproperty
    def XBC(cls):
        return cls("XBC")
    @schemas.classproperty
    def XBD(cls):
        return cls("XBD")
    @schemas.classproperty
    def XTS(cls):
        return cls("XTS")
    @schemas.classproperty
    def XXX(cls):
        return cls("XXX")
    @schemas.classproperty
    def XAU(cls):
        return cls("XAU")
    @schemas.classproperty
    def XPD(cls):
        return cls("XPD")
    @schemas.classproperty
    def XPT(cls):
        return cls("XPT")
    @schemas.classproperty
    def XAG(cls):
        return cls("XAG")
