# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import uuid  # noqa: F401
from datetime import date, datetime  # noqa: F401

import frozendict  # noqa: F401
import typing_extensions  # noqa: F401

from moneykit import schemas  # noqa: F401


class PhoneNumberType(schemas.EnumBase, schemas.StrSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """

    class MetaOapg:
        enum_value_to_name = {
            "home": "HOME",
            "work": "WORK",
            "mobile": "MOBILE",
            "other": "OTHER",
        }

    @schemas.classproperty
    def HOME(cls):
        return cls("home")

    @schemas.classproperty
    def WORK(cls):
        return cls("work")

    @schemas.classproperty
    def MOBILE(cls):
        return cls("mobile")

    @schemas.classproperty
    def OTHER(cls):
        return cls("other")
