
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-04T14:24:00-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5869f3fe554b34a1732557078bf7a30272915f6f",
 "version": "2.10.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
