
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-02T20:20:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "eeca0ae106b17659160345ad0650647650b52925",
 "version": "1.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
