
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-04T04:34:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac454aa9250b3bd5c3b60e7d8aa306f3936c565b",
 "version": "0.29.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
