DATA_INDEX_ENDPOINT = "/dataindex"
DATA_INDEX_STATUS_ENDPOINT = f"{DATA_INDEX_ENDPOINT}/status"
PROCESS_DATA_INDEX_ENDPOINT = f"{DATA_INDEX_ENDPOINT}/process"
UPLOAD_PRE_SIGNED_URL_ENDPOINT = f"{DATA_INDEX_ENDPOINT}/presign"
