from setuptools import setup,find_packages

setup(
    name='eobi',
    version='1.0.0',
    description='...',
    author='Autogon Inc',
    author_email='developer@autogon.ai',
    packages=find_packages(),
    install_requires=[
            'catboost==1.1.1',
            'contourpy==1.0.7',
            'cycler==0.11.0',
            'fonttools==4.39.3',
            'graphviz==0.20.1',
            'joblib==1.2.0',
            'kiwisolver==1.4.4',
            'lightgbm==3.3.5',
            'matplotlib==3.7.1',
            'numpy==1.24.3',
            'packaging==23.1',
            'pandas==2.0.1',
            'Pillow==9.5.0',
            'plotly==5.14.1',
            'pyparsing==3.0.9',
            'python-dateutil==2.8.2',
            'pytz==2023.3',
            'scikit-learn==1.2.2',
            'scipy==1.10.1',
            'six==1.16.0',
            'tenacity==8.2.2',
            'threadpoolctl==3.1.0',
            'tzdata==2023.3',
            'xgboost==1.7.5',
    ],
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
)
