
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-05T08:27:53-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "f1e8e830b071829a39b0fa9c7f6f2ec40aa56cc0",
 "version": "0.0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
