
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-04T12:03:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3e0b8c6ef0b51b1da63e4d7b64dd18cbdf50074",
 "version": "7.25.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
