# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b'75g\xbf'
full_git_hash = '373567bfd9538a58ee1b8e7bd6de11fc84288be9'
git_branch = 'HEAD'
dirty = False
