# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import uuid  # noqa: F401
from datetime import date, datetime  # noqa: F401

import frozendict  # noqa: F401
import typing_extensions  # noqa: F401

from moneykit import schemas  # noqa: F401

class LinkError(schemas.EnumBase, schemas.StrSchema):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """

    @schemas.classproperty
    def SYSTEM_ERROR(cls):
        return cls("system_error")
    @schemas.classproperty
    def PROVIDER_ERROR(cls):
        return cls("provider_error")
    @schemas.classproperty
    def INSTITUTION_ERROR(cls):
        return cls("institution_error")
    @schemas.classproperty
    def USER_ERROR(cls):
        return cls("user_error")
    @schemas.classproperty
    def AUTH_EXPIRED(cls):
        return cls("auth_expired")
    @schemas.classproperty
    def INCOMPLETE(cls):
        return cls("incomplete")
    @schemas.classproperty
    def PAYMENT_ERROR(cls):
        return cls("payment_error")
