__app_name__ = "LinkChecker-GUI"
__version__ = "10.0.0a4"
__release_date__ = "2023-05-03"
__copyright_year__ = "2023"
__author__ = "LinkChecker Authors"
__url__ = "https://github.com/linkchecker/linkchecker-gui"
