
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-01T04:19:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f94c6e2dc43dc28309cd4c4b44359a140545573a",
 "version": "1.18.4.post0.dev24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
