from .AegosPy import A_Gmail
from .AegosPy import A_Yahoo
from .AegosPy import A_Aol
from .AegosPy import A_Hotmail
from .AegosPy import A_MailRu
from .AegosPy import CheckTik
from .AegosPy import CheckInsta
from .AegosPy import GetInfoTik
from .AegosPy import GetInfoInsta
from .AegosPy import GetListInsta_FG
from .AegosPy import GetListTik_FG
from .AegosPy import GetListInsta_FS