
echolocator__Events_TABS_CREATED_EVENT = "echolocator__Events_TABS_CREATED_EVENT";
echolocator__Events_TAB_OPENED = "echolocator__Events_TAB_OPENED";
echolocator__Events_JOB_WAS_DELETED_EVENT = "echolocator__Events_JOB_WAS_DELETED_EVENT";
echolocator__Events_IMAGE_PICKED_EVENT = "echolocator__Events_IMAGE_PICKED_EVENT";
echolocator__Events_IMAGE_PREVIOUS_OR_NEXT_EVENT = "echolocator__Events_IMAGE_PREVIOUS_OR_NEXT_EVENT";
echolocator__Events_NEW_WORKFLOW_EVENT = "echolocator__Events_NEW_WORKFLOW_EVENT";
