#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pink', 'pink.limits', 'pink.tasks']

package_data = \
{'': ['*']}

install_requires = \
['loop-rate-limiters >=0.1.0',
 'numpy >=1.19.0',
 'pin >=2.6.3',
 'qpsolvers >=2.5.0',
 'quadprog >=0.1.11']

setup(name='pin-pink',
      version='0.11.0',
      description='Python inverse kinematics for your robot model based on Pinocchio.',
      author=None,
      author_email='Stéphane Caron <stephane.caron@normalesup.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.7',
     )
