
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-30T22:08:00-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "c7a25bf3e2e9d45091a055c58a522c1aea365cc4",
 "version": "2.11.1b5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
